---
- name: Config Server
  hosts: all
  vars: 
    default_container_image: ubuntu


  tasks: 
  - name: Update Dependecies
    ansible.builtin.apt:
      update_cache: yes
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present
  - name: Run docker compose
    command: cd /app/monitoring
